# Generated by Django 4.1.4 on 2023-01-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_model',
            new_name='MainModel',
        ),
        migrations.AlterModelOptions(
            name='mainmodel',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
