# Generated by Django 4.1.4 on 2023-01-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_main_model_mainmodel_alter_mainmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='image',
            field=models.FileField(upload_to='main/static/img/'),
        ),
    ]
