# Generated by Django 4.1.4 on 2023-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mainmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
